# Configuration for x86_64-linux-musl toolchain build
# DO NOT edit this file directly. Instead, create a local.mk file to override settings.

# Component versions are not overridable via local.mk.
AUTOCONF_VERSION := 2.69
BINUTILS_VERSION := 2.38
GCC_VERSION := 12.1.0
PKGCONFIG_VERSION := 0.29.2
LIBTOOL_VERSION := 2.4.7

ARCH = x86_64
TOOLCHAIN = $(ARCH)-linux-musl

BUILD_DIR = $(CURDIR)/build
TOOL_ROOT = $(CURDIR)/toolchain

MUSL_GIT_URL = https://github.com/aar10n/osdev-musl.git
MUSL_GIT_BRANCH = master

HOST_OS = $(shell uname -s | tr 'A-Z' 'a-z')
HOST_ARCH = $(shell uname -m)

# On macOS, we need real GCC over Apple clang for building GCC since
# clang is not compatible without patches.
ifeq ($(HOST_OS),darwin)
    HOST_CC ?= $(shell which gcc-14 gcc-13 gcc-12 2>/dev/null | head -1)
    HOST_CXX ?= $(shell which g++-14 g++-13 g++-12 2>/dev/null | head -1)
    ifeq ($(HOST_CC),)
        $(error "GCC not found on macOS host. Please set HOST_CC to point to a GCC installation.")
    endif
    ifeq ($(HOST_CXX),)
        $(error "GCC not found on macOS host. Please set HOST_CXX to point to a GCC installation.")
    endif
else
    HOST_CC ?= gcc
    HOST_CXX ?= g++
endif

NPROC = $(shell nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 4)

-include local.mk
